Models/ViewModels/ColaboradorModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;

namespace MVCCrud.Models
{
    public class ColaboradorModel
    {
        [Key]
        public int ID_Colaborador { get; set; }
        [Required]
        public string Nombres { get; set; }
        [Required]
        public string Apellidos { get; set; }
        [Required]
        [DataType(DataType.Date)]
        [Display(Name = "Fecha de Nacimiento")]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public DateTime FechaNacimiento { get; set; }
        [Display(Name = "Estado Civil")] 
        public string EstadoCivil { get; set; }
        [Display(Name = "Grado Académico")]
        public string GradoAcademico { get; set; }
        public string Direccion { get; set; }

    }
}

Models/ViewModels/ListColaboradoresModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;

namespace MVCCrud.Models
{
    public class ListColaboradoresModel
    {
        [Key]
        public int ID_Colaborador { get; set; }
        [Required]
        public string Nombres { get; set; }
        [Required]
        public string Apellidos { get; set; }
        [Required]
        public DateTime FechaNacimiento { get; set; }
        public string EstadoCivil { get; set; }
        public string GradoAcademico { get; set; }
        public string Direccion { get; set; }

    }
}

Controllers/ColaboradoresController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MVCCrud.Models;

namespace MVCCrud.Controllers
{
    public class ColaboradoresController : Controller
    {
        // GET: Colaboradores
        public ActionResult Index()
        {
            List<ListColaboradoresModel> lst;

            using (Crud_App_EspEntities db = new Crud_App_EspEntities())
            {
                lst = (from d in db.Colaboradores
                           select new ListColaboradoresModel
                           {
                               ID_Colaborador = d.ID_Colaborador,
                               Nombres = d.Nombres,
                               Apellidos = d.Apellidos,
                               FechaNacimiento = d.FechaNacimiento,
                               EstadoCivil = d.EstadoCivil,
                               GradoAcademico = d.GradoAcademico,
                               Direccion = d.Direccion
                           }).ToList();
            }

            return View(lst);
        }

        public ActionResult Nuevo() 
        {
            return View();
        }

        [HttpPost]
        public ActionResult Nuevo(ColaboradorModel model) 
        {
            try
            {
                if (ModelState.IsValid)
                {
                    using (Crud_App_EspEntities db = new Crud_App_EspEntities())
                    {
                        var nColaborador = new Colaboradores();
                        nColaborador.Nombres = model.Nombres;
                        nColaborador.Apellidos = model.Apellidos;
                        nColaborador.FechaNacimiento = model.FechaNacimiento;
                        nColaborador.EstadoCivil = model.EstadoCivil;
                        nColaborador.Direccion = model.Direccion;
                        nColaborador.GradoAcademico = model.GradoAcademico;
                        nColaborador.Fecha_Creacion = DateTime.Now;

                        db.Colaboradores.Add(nColaborador);
                        db.SaveChanges();
                    }


                    return Redirect("~/colaboradores/");
                }

                return View();
            } 
            catch (Exception ex)
            {
                throw new Exception(ex.Message);
            }
        }

        public ActionResult Editar(int Id)
        {
            ColaboradorModel model = new ColaboradorModel();
            using (Crud_App_EspEntities db = new Crud_App_EspEntities())
            {
                var oColaborador = db.Colaboradores.Find(Id);
                model.ID_Colaborador = oColaborador.ID_Colaborador;
                model.Nombres = oColaborador.Nombres;
                model.Apellidos = oColaborador.Apellidos;
                model.FechaNacimiento = oColaborador.FechaNacimiento;
                model.EstadoCivil = oColaborador.EstadoCivil;
                model.Direccion = oColaborador.Direccion;
                model.GradoAcademico = oColaborador.GradoAcademico;
            }

            return View(model);
        }

        [HttpPost]
        public ActionResult Editar(ColaboradorModel model)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    using (Crud_App_EspEntities db = new Crud_App_EspEntities())
                    {
                        var nColaborador = db.Colaboradores.Find(model.ID_Colaborador);
                        nColaborador.Nombres = model.Nombres;
                        nColaborador.Apellidos = model.Apellidos;
                        nColaborador.FechaNacimiento = model.FechaNacimiento;
                        nColaborador.EstadoCivil = model.EstadoCivil;
                        nColaborador.Direccion = model.Direccion;
                        nColaborador.GradoAcademico = model.GradoAcademico;
                        nColaborador.Fecha_Creacion = DateTime.Now;

                        db.Entry(nColaborador).State = System.Data.Entity.EntityState.Modified;
                        db.SaveChanges();
                    }


                    return Redirect("~/colaboradores/");
                }

                return View();
            }
            catch (Exception ex)
            {
                throw new Exception(ex.Message);
            }
        }

        [HttpGet]
        public ActionResult Eliminar(int Id)
        {
            using (Crud_App_EspEntities db = new Crud_App_EspEntities())
            {
                var oColaborador = db.Colaboradores.Find(Id);
                db.Colaboradores.Remove(oColaborador);
                db.SaveChanges();
            }

            return Redirect("~/colaboradores/");
        }
    }
}

Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MVCCrud.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

Views/Colaboradores/Editar.cshtml
@model MVCCrud.Models.ColaboradorModel

@{
    ViewBag.Title = "Editar";
}

<h2>@ViewBag.Title</h2>


@using (Html.BeginForm("Editar", "Colaboradores", FormMethod.Post))
{
    <div class= ="row">
        <div class="col-md-12">
            @Html.HiddenFor(d => d.ID_Colaborador)
            <div class="form-row">
                <div class="form-group col-md-6">
                    @Html.LabelFor(d => d.Nombres)
                    @Html.TextBoxFor(d => d.Nombres, "", new { @class = "form-control" })
                    @Html.ValidationMessageFor(d => d.Nombres, "", new { @class = "text-danger" })
                </div>

                <div class="form-group col-md-6">
                    @Html.LabelFor(d => d.Apellidos)
                    @Html.TextBoxFor(d => d.Apellidos, "", new { @class = "form-control" })
                    @Html.ValidationMessageFor(d => d.Apellidos, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(d => d.Direccion)
                @Html.TextBoxFor(d => d.Direccion, "", new { @class = "form-control" })
                @Html.ValidationMessageFor(d => d.Direccion, "", new { @class = "text-danger" })
            </div>
            <div class="form-group">
                @Html.LabelFor(d => d.GradoAcademico)
                @Html.TextBoxFor(d => d.GradoAcademico, "", new { @class = "form-control" })
            </div>
            <div class="form-row">
                <div class="form-group col-md-6">
                    @Html.LabelFor(d => d.EstadoCivil)
                    @Html.TextBoxFor(d => d.EstadoCivil, "", new { @class = "form-control" })
                </div>

                <div class="form-group col-md-6">
                    @Html.LabelFor(d => d.FechaNacimiento)
                    @Html.EditorFor(d => d.FechaNacimiento, "", new { @class = "form-control" })
                    @Html.ValidationMessageFor(d => d.FechaNacimiento, "", new { @class = "text-danger" })
                </div>
            </div>
            <hr />
            <br />
            <div style="text-align: right">
                <input value="Guardar" class="btn btn-primary" type="submit" />
            </div>
        </div>
    </div>
}

Views/Colaboradores/Index.cshtml
@model List<MVCCrud.Models.ListColaboradoresModel>

@{
    ViewBag.Title = "Listado de Colaboradores";
}

<h2>@ViewBag.Title</h2>

<div class="row" style="text-align: right; padding: 5px">
    <a href="~/colaboradores/nuevo" class="btn btn-primary">Nuevo</a>
</div>

<div class="row">
    <div class="col-md-12">
        <table class="table table-responsive">
            <tr>
                <th># ID</th>
                <th>Nombres</th>
                <th>Apellidos</th>
                <th>Fecha de Nacimiento</th>
                <th>Estado Civil</th>
                <th>Grado Académico</th>
                <th>Dirección</th>
            </tr>
            @foreach (var item in Model)
            {
                <tr>
                    <td>@item.ID_Colaborador</td>
                    <td>@item.Nombres</td>
                    <td>@item.Apellidos</td>
                    <td>@item.FechaNacimiento</td>
                    <td>@item.EstadoCivil</td>
                    <td>@item.GradoAcademico</td>
                    <td>@item.Direccion</td>
                    <td>
                        <a href="~/colaboradores/editar/@item.ID_Colaborador" class="btn btn-default">Editar</a>
                        <a href="~/colaboradores/eliminar/@item.ID_Colaborador" class="btn btn-danger">Eliminar</a>
                    </td>
                </tr>
            }
        </table>
    </div>
</div>

Views/Colaboradores/Nuevo.cshtml
@model MVCCrud.Models.ColaboradorModel

@{
    ViewBag.Title = "Nuevo";
}

<h2>@ViewBag.Title</h2>


@using (Html.BeginForm("Nuevo", "Colaboradores", FormMethod.Post))
{
<div class=="row">
    <div class="col-md-12">
        <div class="form-row">
            <div class="form-group col-md-6">
                @Html.LabelFor(d => d.Nombres)
                @Html.TextBoxFor(d => d.Nombres, "", new { @class = "form-control" })
                @Html.ValidationMessageFor(d => d.Nombres, "", new { @class = "text-danger" })
            </div>

            <div class="form-group col-md-6">
                @Html.LabelFor(d => d.Apellidos)
                @Html.TextBoxFor(d => d.Apellidos, "", new { @class = "form-control" })
                @Html.ValidationMessageFor(d => d.Apellidos, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(d => d.Direccion)
            @Html.TextBoxFor(d => d.Direccion, "", new { @class = "form-control" })
            @Html.ValidationMessageFor(d => d.Direccion, "", new { @class = "text-danger" })
        </div>
        <div class="form-group">
            @Html.LabelFor(d => d.GradoAcademico)
            @Html.TextBoxFor(d => d.GradoAcademico, "", new { @class = "form-control" })
        </div>
        <div class="form-row">
            <div class="form-group col-md-6">
                @Html.LabelFor(d => d.EstadoCivil)
                @Html.TextBoxFor(d => d.EstadoCivil, "", new { @class = "form-control" })
            </div>

            <div class="form-group col-md-6">
                @Html.LabelFor(d => d.FechaNacimiento)
                @Html.EditorFor(d => d.FechaNacimiento, "", new { @class = "form-control" })
                @Html.ValidationMessageFor(d => d.FechaNacimiento, "", new { @class = "text-danger" })
            </div>
        </div>
        <hr />
        <br />
        <div style="text-align: right">
            <input value="Guardar" class="btn btn-primary" type="submit" />
        </div>
    </div>
</div>
}

Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Mi aplicación ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Nombre de la aplicación", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Inicio", "Index", "Home")</li>
                    <li>@Html.ActionLink("Acerca de", "About", "Home")</li>
                    <li>@Html.ActionLink("Contacto", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Mi aplicación ASP.NET</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>